### ISSUE TITLE
Add support for alternative DNS resolvers in lego

### ISSUE THREAD

**Issue by lozzd** [tisba/fritz-tls#21]
Hey there!
Thanks for putting this together! 

There is an option in lego that allows for alternative DNS resolvers to be used. This option is not passed through fritz-tls - would it be possible to allow that? 
The reason they allow it is to override the local system resolvers to solve the DNS challenge. This would be very helpful to avoid DNS TTL issues - I currently have to have the polling interval set to every couple of minutes, but wait up to 2 hours for propogation to take place. 
If I could override the resolvers to point directly to my DNS' providers namesevers, it would speed up the process considerably. 

It's referenced in the lego repo here:
https://github.com/go-acme/lego/blob/83c626d9a1889fa499bc9c97bc2fdea965307002/cmd/flags.go#L97-L99

I'm a little confused also because I used https://github.com/kchristensen/udm-le to automate the certificate generation (also uses lego in the backend) for another device, and for some reason lego automatically decided to go to my authoratative nameservers directly to resolve the record. So I'm not 100% sure why that behaviour wasn't matched here - it used my system resolvers instead. 
There's references to that in the code hre: https://github.com/go-acme/lego/blob/83c626d9a1889fa499bc9c97bc2fdea965307002/challenge/dns01/precheck.go#L70
https://github.com/go-acme/lego/blob/83c626d9a1889fa499bc9c97bc2fdea965307002/challenge/dns01/nameserver.go#L96-L97

**Comment by tisba** [comment]
Interesting 🤔 

I think I first have to update and fix some dependencies, but then I'll look more closely into this matter. AFAIK there should be no reason not to support this. Quite the contrary, that the authoritative name server is not used sounds more like a bug.

**Comment by lozzd** [comment]
Yes I'm a bit confused and was trying to dig through the lego source to see why it behaves differently on these two systems. On one, it defaulted to going to the authoratative nameservers... and on the other, it used the system resolver. I can't figure out why the difference in behaviour. 

It's not the end of the world, it just means waiting 1.5 hours for full propogation to have completed instead of ~10-15 mins for the authoratative nameserver to show the new record being there.

**Comment by tisba** [comment]
Hey @lozzd 👋 

Can you check out if [v0.10.0](https://github.com/tisba/fritz-tls/releases/tag/v0.10.0) solves this issue for you? I just published a new version.

In https://github.com/tisba/fritz-tls/commit/afcc8d3e274eb88b91725e13a01f581f99b82772 I added the option to use a custom DNS resolver. In my testing it got picked up, so I hope this solves your issue.

PS: Be aware that I dropped `--auto-cert` and made it the default with this release as well. I got tiered typing it over and over again 🙈

**Comment by lozzd** [comment]
Thanks, I'll give it a shot! 
It's still using my system resolvers by default (tried that firt) versus on that other system where it immediately fell back to using the authoratative nameservers, I really don't understand why. It'd make way more sense if it always went straight to the authoratative to skip any caching issues. 🤔 

Hopefully it'll work, because now the solving of the DNS takes so long that the Fritzbox session has expired by the time the DNS caches have cleared, so the upload fails! 🙄  I guess if that continues it raises the question - chicken or egg - login to the Fritzbox to see if the auth works, or skip that, try the cert first, and then hope the login works - or just have code to renew the session I guess. 

Thanks again!

**Comment by lozzd** [comment]
Hmmm - well. This was a vast improvement, it took just 22 minutes to verify the DNS entries - amazing! 
But upload still failed because I got kicked back to the login page on the FritzBox. That's really bizare - this worked once! With a much longer propogation time. I wonder what the session expiry is on the Fritzbox?

**Comment by tisba** [comment]
I think I have to read more of `lego` code to properly understand this. The resolver option I've added is only used for the client to check if the entry has been propagated and then triggers the check by Let's Encrypt. Let's Encrypt is of corse not using the resolver you specify, because that would defeat the whole verification purpose 😉 

I'm not sure about the timeout duration. My guess is something around 10 minutes. The problem with the timed out session is maybe a slightly different one. My initial idea was that I want to check that the login works first before continuing. But it should be no problem to re-authenticate if the session is lost 🤔

**Comment by tisba** [comment]
Could you try `--dns-resolver` with the authoritative name server for the domain you're trying to obtain a cert for? That should be much quicker if this is a DNS propagation issue.

**Comment by tisba** [comment]
I've dug a bit deeper into the `lego` code and this is what I think is going on:

1. lego is doing a "pre check" to see if the DNS entry has been propagated. This is being handled by `dns01.Solve` in https://github.com/go-acme/lego/blob/v4.5.3/challenge/dns01/dns_challenge.go#L131-L137
2. First the system resolver (or the resolver specified by `--dns-resolver` in `fritz-tls`) is being used to check for the updated DNS entry, see `checkDNSPropagation` https://github.com/go-acme/lego/blob/v4.5.3/challenge/dns01/precheck.go#L55-L76.
3. if this check is successful, only then are the authoritative name servers asked directly in `checkAuthoritativeNss` https://github.com/go-acme/lego/blob/v4.5.3/challenge/dns01/precheck.go#L79-L110

As far as I can tell, there is no way to change this behaviour. I my guess would be, that they don't want to hit authoritative name servers unnecessarily. I'm collecting a bit more information and will open an issue with lego for clarification.

In the meantime, I just pushed [v0.11.0](https://github.com/tisba/fritz-tls/releases/tag/v0.11.0) which should work as a workaround for you: The FRITZ!Box session is checked before the certificate upload and another login is performed if necessary. It won't be a speed up in your case, but it might help to succeed.
